### DISCUSSION TITLE
Error during borg create after changing base directory and user

### DISCUSSION THREAD

**Discussion by rcdailey** [borgbackup/borg#6735] [Q&A]
On my Synology NAS, I was running `borgmatic` as the root user. I switched the task to a non-root user instead. However, I get failures when I run `borgmatic --create --prune` (see below).

I moved the entire borg directory & files to a new location and did `chmod` & `chown` to switch the user and permissions.

I'm not sure why I still get this failure. Borg is very difficult to use with mysterious errors and no clear way to recover from them. I'm at the end of my rope.

```
summary:
/volume2/BorgBackup/borgmatic.yml: Error running configuration file
snip.repo.borgbase.com:repo: Error running actions for repository
...
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'repo'
Remote: Resolved repository path to '/srv/repos/snip/repo'
Remote: Verified integrity of /srv/repos/snip/repo/index.3961
TAM-verified manifest
security: read previous location 'ssh://snip.repo.borgbase.com/./repo'
security: read manifest timestamp '2022-05-31T20:10:23.649482'
security: determined newest manifest timestamp as 2022-05-31T20:10:23.649482
security: repository checks ok, allowing access
Creating archive at "snip.repo.borgbase.com:repo::diskstation-2022-05-31T15:10:27.383495"
Verified integrity of /volume2/BorgBackup/.borg/.cache/borg/2d931852622812096ee5dec8e4e6b12b2d272e4f3c1f9e7ec694380368686f30/chunks
Reading files cache ...
Verified integrity of /volume2/BorgBackup/.borg/.cache/borg/2d931852622812096ee5dec8e4e6b12b2d272e4f3c1f9e7ec694380368686f30/files
security: read previous location 'ssh://snip.repo.borgbase.com/./repo'
security: read manifest timestamp '2022-05-31T20:10:23.649482'
security: determined newest manifest timestamp as 2022-05-31T20:10:23.649482
security: repository checks ok, allowing access
Processing files ...
Remote: Cleaned up 0 uncommitted segment files (== everything after segment 3961).
Remote: Verified integrity of /srv/repos/snip/repo/hints.3961
Remote: Storage quota: 867.42 GB out of 3.95 TB used.
RemoteRepository: 217.64 MB bytes sent, 8.51 kB bytes received, 453 messages sent
Local Exception
Traceback (most recent call last):
  File "/volume2/@appstore/borgbackup/env/lib/python3.10/site-packages/borg/helpers/fs.py", line 290, in os_open
Command 'borg create --exclude-from /tmp/tmpws6g1vs1 --debug --show-rc snip.repo.borgbase.com:repo::{hostname}-{now:%Y-%m-%dT%H:%M:%S.%f} /volume2/homes/user1 /volume2/nextcloud/user2/files /volume2/nextcloud/user1/files' returned non-zero exit status 2.

Need some help? https://torsion.org/borgmatic/#issues
```

The YAML I use is:

```yml
location:
  repositories:
    - snip.repo.borgbase.com:repo
  source_directories:
    - /volume2/homes/user1
    - /volume2/nextcloud/user1/files
    - /volume2/nextcloud/user2/files
  exclude_patterns:
    - /volume2/homes/user1/Google Drive Backup

storage:
  ssh_command: ssh -i /volume2/BorgBackup/id_synology_borgbase
  encryption_passphrase: "snip"
  borg_base_directory: /volume2/BorgBackup/.borg

retention:
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 6

consistency:
  checks:
    - repository
```
