### DISCUSSION TITLE
How to test excluded_from is working?

### DISCUSSION THREAD

**Discussion by littlesandra88** [borgbackup/borg#7539] [Q&A] [answered]
Dear all =)

I have created a `excluded` file with lines such as
```
*/.npm/*
*/.librewolf/*.default-release/storage/default
*/.config/Slack/Cache
```
and I use borg with borgmatic where I use this config
```
location:
    source_directories:
        - /home/a/

    repositories:
        - path: /home/a/borg/dotfiles

    atime: false
    ctime: true
    birthtime: true

    exclude_patterns:
         - '/home/a/[a-zA-Z0-9]*'

    exclude_from:
        - /home/a/borg/exclude

storage:
    encryption_passphrase: x
    compression: zstd

retention:
    keep_daily: 7
```
and I test it like so
```
borgmatic -v 1 create --stats -c dotfiles.yaml
borgmatic --no-color list --archive latest -c dotfiles.yaml | grep "Slack/Cache"
```
which gives lines such as
```
-rw------- a      a          4701 Mon, 2023-04-24 07:23:13 home/a/.config/Slack/Cache/Cache_Data/bdb5732c1c15f8ad_0
-rw------- a      a          4893 Mon, 2023-04-24 08:17:42 home/a/.config/Slack/Cache/Cache_Data/94d4655c3e0971eb_0
-rw------- a      a          4700 Mon, 2023-04-24 08:17:42 home/a/.config/Slack/Cache/Cache_Data/cf709c297705ddc6_0
```

and for some reason `Slack/Cache` is not excluded.

**Question**

Can anyone figure out what I am doing wrong?

Hugs,
Sandra =)
