### DISCUSSION TITLE
Exclude everything except a few dirs

### DISCUSSION THREAD

**Discussion by littlesandra88** [borgbackup/borg#7541] [Q&A] [answered]
Dear all =)

I would like to make a backup of a few specific directories. So I have tried the following that gives me empty backups.
```
location:
    source_directories:
        - /home/a/

    repositories:
        - path: /home/a/borg/dotfiles_large

    atime: false
    ctime: true
    birthtime: true

    patterns_from:
        - /home/a/borg/dotfiles_large.patterns

storage:
    encryption_passphrase: x
    compression: zstd

retention:
    keep_daily: 2
```
and `dotfiles_large.patterns` contains
```
P sh

R /home/a/

# exclude everything also .files and .dirs
- *

# include
+ */.config/google-chrome*
```
**Question**

Can anyone see why `.config/google-chrome*` isn't included in the backup?

Hugs,
Sandra =)
