### ISSUE TITLE
Offer flatpak and snap version

### ISSUE THREAD

**Issue by rugk** [borgbackup/borg#2429]
Currently you offer a binary for easy usage, but with flatpak and snap becoming a (big?) alternative in the future, it would also be nice if you offer a flatpak and snap version of borg.

**Comment by lightonflux** [comment]
Quick and dirty snap that does not duplicate dependency and build setup debugging (because it uses the binary releases):


### Project structure with rights
```
root@snap:~/borg-snap# tree -p
.
|-- [-rw-r--r--]  snapcraft.yaml
`-- [drwxr-xr-x]  source
    |-- [-rwxr-xr-x]  arch-switch.sh
    |-- [-rwxr-xr-x]  borg-linux32
    `-- [-rwxr-xr-x]  borg-linux64

1 directory, 4 files
```

### Script for "multiarch"
```
root@snap:~/borg-snap# cat source/arch-switch.sh
#!/bin/sh

case "$SNAP_ARCH" in
    "amd64") $SNAP/bin/borg-linux64 "$@"
    ;;
    "i386") $SNAP/bin/borg-linux32 "$@"
    ;;
    *)
        echo "Unsupported architecture for this borg snap"
        exit 1
    ;;
esac
```

### snapcraft file
```
root@snap:~/borg-snap# cat snapcraft.yaml
name: borg
version: '1'
summary: Borg is a backup program with many features
description: |
  The main goal of Borg is to provide an efficient and secure way to backup data. The data deduplication technique usedmakes Borg suitable for daily backups since only changes are stored. The authenticated encryption technique makes it suitable for backups to not fully trusted targets.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures: ["amd64", "i386"]

apps:
  borg:
    command: bin/borg-launch
    plugs: ["home", "removable-media"]

parts:
  borg:
    source: source/
    plugin: dump
    organize:
      arch-switch.sh: bin/borg-launch
      borg-linux64: bin/borg-linux64
      borg-linux32: bin/borg-linux32
```

Tested, works on 32 and 64 bit systems.


Was it really quick? No, because i wanted to include both arch in one package. And i had to setup a snapcraft environment which meant organising an ubuntu installation.

Is it really dirty? Yes. It is larger because the binaries do not depend on the snap "runtime" (ubuntu core that is) and because snapcraft included unnecessary libs (114KB):
```

|-- [drwxr-xr-x 4.0K]  prime
|   |-- [drwxr-xr-x 4.0K]  bin
|   |   |-- [-rwxr-xr-x  220]  borg-launch
|   |   |-- [-rwxr-xr-x  12M]  borg-linux32
|   |   `-- [-rwxr-xr-x  13M]  borg-linux64
|   |-- [-rwxr-xr-x  321]  command-borg.wrapper
|   |-- [drwxr-xr-x 4.0K]  lib
|   |   `-- [drwxr-xr-x 4.0K]  x86_64-linux-gnu
|   |       |-- [-rw-r--r--  14K]  libdl.so.2
|   |       `-- [-rw-r--r-- 110K]  libz.so.1
|   `-- [drwxr-xr-x 4.0K]  meta
|       |-- [drwxr-xr-x 4.0K]  gui
|       `-- [-rw-r--r--  500]  snap.yaml
```

I don't think that it is beneficial to compile borg with snapcraft, as this means some hours setup that could be spend improving the normal build system. But it probably makes sense to make two or three snaps for each architecture, because it saves the user 10-20MB  disk space. 

Another problem is that if you want to make the snap available for all users [you need to change](https://snapcraft.io/docs/build-snaps/publish) from `confinement: devmode` to `confinement: strict`. Then borg can only access the users home (not true for /root) and removable media under `/media` and `/run`. Afaik there isn't a "plug" for the whole file system.
