### ISSUE TITLE
add timeout to gh actions jobs

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borg#5548]
```
jobs:
  jobid:
    name: ...
    timeout-minutes: 60
```

just to avoid it runs 6h if sth goes wrong (which happens randomly in gh actions).
