### ISSUE TITLE
base64 encoded passphrase is incorrect when used with BORG_PASSPHRASE or BORG_PASSCOMMAND

### ISSUE THREAD

**Issue by Juho-J** [borgbackup/borg#7415]
## Have you checked borgbackup docs, FAQ, and open GitHub issues?

Yes

## Is this a BUG / ISSUE report or a QUESTION?

BUG / ISSUE (I think)

#### Your borg version (borg -V).

1.2.3

#### Operating system (distribution) and version.

Almalinux 9.1 minimal

#### How much data is handled by borg?

None at the moment

## Describe the problem you're observing.

Using base64 encoded passphrase with BORG_PASSCOMMAND or BORG_PASSPHRASE is not working. With no encoding it works fine.

#### Can you reproduce the problem? If so, describe how. If not, describe troubleshooting steps you took before opening the issue.

Yes. 

I have a file ~/.borg_passphrase with contents created like in the example at [here](https://borgbackup.readthedocs.io/en/stable/faq.html#how-can-i-specify-the-encryption-passphrase-programmatically). 

Lets say I encoded the passphrase `test1234` into base64 which would result in `dGVzdDEyMzQK` which was appended to the `.borg_passphrase` file with no new lines what so ever.

I am executing this script as systemd service `backup.service`:
```
#!/bin/bash

name=$(/usr/bin/date +%d-%m-%Y_%H:%M:%S)
export BORG_PASSPHRASE=$(/usr/bin/cat /home/user/.borg_passphrase)

# Also tried this with the same results:
# export BORG_PASSCOMMAND="cat /home/user/.borg_passphrase"

/usr/bin/borg create /home/user/server/backup/borg::$name /home/user/server/data
```

Once systemd runs this script I get the following output when I check `systemctl status backup.service`:
```
Mar 07 12:01:24 server backup.sh[30414]: passphrase supplied in BORG_PASSPHRASE, by BORG_PASSCOMMAND or via BORG_PASSPHRASE_FD is incorrect.
Mar 07 12:01:24 server systemd[1]: backup.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 07 12:01:24 server systemd[1]: backup.service: Failed with result 'exit-code'.
```

If my `.borg_passphrase` contents were just in plain text (E.g. `test1234`) the script would run fine and the backup is created succesfully. 

Is this a bug/issue or just sone base64 encoding problem I am having?

I am generating the `.borg_passphrase` file with ansible basically with a task like this:
```
    - name: Create .borg_passphrase
      ansible.builtin.lineinfile:
        create: true
        path: "{{ home }}/.borg_passphrase"
        line: "{{ borg_passphrase_base64 }}" # This is equivelant to: dGVzdDEyMzQK
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: u=rw,g-rwx,o-rwx
```

Thanks for your help in advance!
